### ISSUE TITLE
If this is IDEA plugin for SlimEnum, where is SlimEnum .jar sources?

### ISSUE THREAD

**Issue by paulvi** [cheblin/SlimEnum#2]
If this is IDEA plugin for SlimEnum, where is SlimEnum .jar sources?

**Comment by cheblin** [comment]
Hi Poul

[the source code you asked for is here](https://github.com/cheblin/SlimEnum/blob/master/src/org/unirail/SlimEnum/SlimEnumCompelition.java)

With Best regards!
