### ISSUE TITLE
What are SlimEnums?

### ISSUE THREAD

**Issue by paulvi** [cheblin/SlimEnum#9]
When search I get 3 links, 2 of them are actually this plugin

![image](https://user-images.githubusercontent.com/1614482/111064893-b4309680-84f1-11eb-9c9f-cf7fac7d9da2.png)
 and  the last is some post by you 3 years ago https://coderanch.com/t/690872/SlimEnum-enum
 
 This is not enough to convince somebody to install plugin.
 So there should be clear explanation What are SlimEnums?
 
 I saw the Youtube video https://www.youtube.com/watch?v=Hzs6OBcvNQE
 that give particular references to `@IntDef` annotation 
 https://developer.android.com/reference/android/support/annotation/IntDef
 that is deprecated already.
 
 So what are SlimEnums? Some dependency? or way to write code?
 
 Please give clear explanation to all potential users without need to watch the video or read all through README,
 that is in first few lines.

**Comment by paulvi** [comment]
Keeping searching about enums on Android I get
https://medium.com/android-news/android-performance-avoid-using-enum-on-android-326be0794dc3
that says about Enum  as evil but and references the same video
but does not mention that enum are converted to int constans by proguard by default, 
see https://stackoverflow.com/questions/32236870/does-proguard-converts-all-enums-to-int-or-needs-to-be-configured-for-this

**Comment by cheblin** [comment]
> So what are SlimEnums? Some dependency? or way to write code?
> 
> Please give clear explanation to all potential users without need to watch the video or read all through README,
> that is in first few lines.

Hello
Exactly this is explained in the [readme ](https://github.com/cheblin/SlimEnum/blob/main/README.md)
Thank you for your note.

**Comment by cheblin** [comment]
>enum are converted to int constans by proguard by default

This is not useful. Developers need these constants at develop time. Underlying libs use these constants too.
And flags. 
If your constants just numbers you can combine them by bitwise operations in a natural manner.

**Comment by paulvi** [comment]
well, tools approach (e.g. proguard) is better that have developers to worry and use different tricks.
But proguard is to be replaced by google, I don't follow how much functional new tool will be.

> If your constants are just numbers you can combine them by bitwise operations in a natural manner.
Yes, that is beauty, good example for README
